/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contact {
  'id' : ContactId,
  'name' : string,
  'createdAt' : Time,
  'mobileNumber' : string,
  'updatedAt' : Time,
  'notes' : string,
  'category' : string,
  'tracked' : boolean,
}
export type ContactId = bigint;
export interface ContactInput {
  'id' : [] | [ContactId],
  'name' : string,
  'mobileNumber' : string,
  'notes' : string,
  'category' : string,
  'tracked' : boolean,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCallerContact' : ActorMethod<[ContactId], undefined>,
  'deleteCallerContacts' : ActorMethod<[Array<ContactId>], undefined>,
  'getCallerContact' : ActorMethod<[ContactId], Contact>,
  'getCallerContactIds' : ActorMethod<[], Array<ContactId>>,
  'getCallerContacts' : ActorMethod<[], Array<Contact>>,
  'getCallerContactsByCategory' : ActorMethod<[string], Array<Contact>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactsOfUser' : ActorMethod<[Principal], Array<Contact>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'manageUserContact' : ActorMethod<[ContactInput], ContactId>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleTrackContact' : ActorMethod<[ContactId], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
