/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactId = IDL.Nat;
export const Time = IDL.Int;
export const Contact = IDL.Record({
  'id' : ContactId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'mobileNumber' : IDL.Text,
  'updatedAt' : Time,
  'notes' : IDL.Text,
  'category' : IDL.Text,
  'tracked' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactInput = IDL.Record({
  'id' : IDL.Opt(ContactId),
  'name' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'notes' : IDL.Text,
  'category' : IDL.Text,
  'tracked' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCallerContact' : IDL.Func([ContactId], [], []),
  'deleteCallerContacts' : IDL.Func([IDL.Vec(ContactId)], [], []),
  'getCallerContact' : IDL.Func([ContactId], [Contact], ['query']),
  'getCallerContactIds' : IDL.Func([], [IDL.Vec(ContactId)], ['query']),
  'getCallerContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getCallerContactsByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Contact)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactsOfUser' : IDL.Func([IDL.Principal], [IDL.Vec(Contact)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'manageUserContact' : IDL.Func([ContactInput], [ContactId], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleTrackContact' : IDL.Func([ContactId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactId = IDL.Nat;
  const Time = IDL.Int;
  const Contact = IDL.Record({
    'id' : ContactId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'mobileNumber' : IDL.Text,
    'updatedAt' : Time,
    'notes' : IDL.Text,
    'category' : IDL.Text,
    'tracked' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactInput = IDL.Record({
    'id' : IDL.Opt(ContactId),
    'name' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'notes' : IDL.Text,
    'category' : IDL.Text,
    'tracked' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCallerContact' : IDL.Func([ContactId], [], []),
    'deleteCallerContacts' : IDL.Func([IDL.Vec(ContactId)], [], []),
    'getCallerContact' : IDL.Func([ContactId], [Contact], ['query']),
    'getCallerContactIds' : IDL.Func([], [IDL.Vec(ContactId)], ['query']),
    'getCallerContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getCallerContactsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Contact)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactsOfUser' : IDL.Func([IDL.Principal], [IDL.Vec(Contact)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'manageUserContact' : IDL.Func([ContactInput], [ContactId], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleTrackContact' : IDL.Func([ContactId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
